package formularios;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
public class Formulario extends javax.swing.JFrame{
conexion miconexion;
Connection con;
ResultSet r;
CallableStatement cst;
PreparedStatement psPrepararSentencias;
 public Formulario() throws ClassNotFoundException, SQLException {
        this.miconexion = new conexion();
 
 initComponents();
 
 
 try{ 
 Class.forName("com.mysql.jdbc.Driver");
 String url="jdbc:Mysql://localhost/empleados";
 con=DriverManager.getConnection(url,"root","");
 JOptionPane.showMessageDialog(null, "Conexion Correcta");
 }
 catch (Exception e){
 
 e.printStackTrace();
 }ResultSet r;
CallableStatement cst;
 }
 /**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code"> 
 private void initComponents() {
 jLabel2 = new javax.swing.JLabel();
 jTextField5 = new javax.swing.JTextField();
 jLabel3 = new javax.swing.JLabel();
 jLabel4 = new javax.swing.JLabel();
 jTextField3 = new javax.swing.JTextField(); jButton1 = new javax.swing.JButton();
 jButton4 = new javax.swing.JButton();
 jTextField1 = new javax.swing.JTextField();
 jLabel1 = new javax.swing.JLabel();
 jLabel5 = new javax.swing.JLabel();
 jTextField2 = new javax.swing.JTextField();
 jButton2 = new javax.swing.JButton();
 setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
 jLabel2.setText("CODIGO");
 jTextField5.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jTextField5ActionPerformed(evt);
 }
 });
 jLabel3.setText("NOMBRE");
 jLabel4.setText("EDAD");
 jTextField3.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jTextField3ActionPerformed(evt);
 }
 });
 jButton1.setText("BUSCAR");
 jButton1.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
     try {
         jButton1ActionPerformed(evt);
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
     } catch (SQLException ex) {
         Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
     }
 }
 });
 jButton4.setText("REGISTRAR");
 jButton4.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jButton4ActionPerformed(evt);
 }
 });
 jLabel1.setText("registro de empleado");
 jLabel5.setText("SUELDO");
 jTextField2.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jTextField2ActionPerformed(evt);
 } });
 jButton2.setText("MODIFICAR");
 jButton2.addActionListener(new java.awt.event.ActionListener() {
 public void actionPerformed(java.awt.event.ActionEvent evt) {
 jButton2ActionPerformed(evt);
 }
 });
 javax.swing.GroupLayout layout = new 
javax.swing.GroupLayout(getContentPane());
 getContentPane().setLayout(layout);
 layout.setHorizontalGroup(
 
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(layout.createSequentialGroup()
 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(layout.createSequentialGroup()
 .addGap(147, 147, 147)
 .addComponent(jButton4, 
javax.swing.GroupLayout.PREFERRED_SIZE, 110, 
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addGap(69, 69, 69)
 .addComponent(jButton1, 
javax.swing.GroupLayout.PREFERRED_SIZE, 94, 
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addGap(44, 44, 44)
 .addComponent(jButton2))
 .addGroup(layout.createSequentialGroup()
 .addGap(43, 43, 43)
 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
 .addGroup(layout.createSequentialGroup()
 .addComponent(jLabel5, 
javax.swing.GroupLayout.PREFERRED_SIZE, 152, 
javax.swing.GroupLayout.PREFERRED_SIZE)
 
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 
javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
 .addComponent(jTextField2, 
javax.swing.GroupLayout.PREFERRED_SIZE, 179, 
javax.swing.GroupLayout.PREFERRED_SIZE))
 .addGroup(layout.createSequentialGroup()
 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) .addComponent(jLabel3, 
javax.swing.GroupLayout.PREFERRED_SIZE, 184, 
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addComponent(jLabel4, 
javax.swing.GroupLayout.PREFERRED_SIZE, 49, 
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addComponent(jLabel2, 
javax.swing.GroupLayout.PREFERRED_SIZE, 111, 
javax.swing.GroupLayout.PREFERRED_SIZE))
 
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addComponent(jTextField5, 
javax.swing.GroupLayout.PREFERRED_SIZE, 179, 
javax.swing.GroupLayout.PREFERRED_SIZE)
 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
 .addComponent(jTextField3, 
javax.swing.GroupLayout.Alignment.LEADING, 
javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
 .addComponent(jTextField1, 
javax.swing.GroupLayout.Alignment.LEADING))))))
 .addGroup(layout.createSequentialGroup()
 .addGap(171, 171, 171)
 .addComponent(jLabel1, 
javax.swing.GroupLayout.PREFERRED_SIZE, 113, 
javax.swing.GroupLayout.PREFERRED_SIZE)))
 .addContainerGap(63, Short.MAX_VALUE))
 );
 layout.setVerticalGroup(
 
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(layout.createSequentialGroup()
 .addGap(13, 13, 13)
 .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 
23, javax.swing.GroupLayout.PREFERRED_SIZE)
 .addGap(18, 18, 18)
 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addComponent(jTextField3, 
javax.swing.GroupLayout.PREFERRED_SIZE, 27, 
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addComponent(jLabel2, 
javax.swing.GroupLayout.PREFERRED_SIZE, 39, 
javax.swing.GroupLayout.PREFERRED_SIZE)) 
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(jLabel3)
 .addComponent(jTextField1, 
javax.swing.GroupLayout.PREFERRED_SIZE, 34, 
javax.swing.GroupLayout.PREFERRED_SIZE))
 .addGap(18, 18, 18)
 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(jLabel4, 
javax.swing.GroupLayout.PREFERRED_SIZE, 39, 
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addComponent(jTextField5, 
javax.swing.GroupLayout.PREFERRED_SIZE, 30, 
javax.swing.GroupLayout.PREFERRED_SIZE))
 
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(jLabel5, 
javax.swing.GroupLayout.PREFERRED_SIZE, 46, 
javax.swing.GroupLayout.PREFERRED_SIZE)
 .addComponent(jTextField2, 
javax.swing.GroupLayout.PREFERRED_SIZE, 39, 
javax.swing.GroupLayout.PREFERRED_SIZE))
 .addGap(53, 53, 53)
 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
 .addComponent(jButton4)
 .addComponent(jButton1))
 .addContainerGap(64, Short.MAX_VALUE))
 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, 
layout.createSequentialGroup()
 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, 
Short.MAX_VALUE)
 .addComponent(jButton2)
 .addGap(63, 63, 63))
 );
 pack();
 }// </editor-fold> 
 private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) { 
     
 }
 // TODO add your handling code here: 
 private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException, SQLException { 
 //registrar
     conexion miconexion = new conexion ();
 String cons = "select = from constacia";
 ResultSet BUSCAR;
    BUSCAR = miconexion.BUSCAR(cons);
 BUSCAR.next();
 String cod=this.jTextField1.getText();
 jTextField1.setText(BUSCAR.getString(1));
 String nom=this.jTextField2.getText();
 jTextField2.setText(BUSCAR.getString(2));
 String edad=this.jTextField3.getText();
 jTextField3.setText(BUSCAR.getString(3));
 String sueldo=this.jTextField5.getText();
 jTextField5.setText(BUSCAR.getString(5));
 try{
 cst=con.prepareCall("{call consulta(?,?,?,?)}");
 cst.setString(1, cod);
 cst.setString(2, nom);
 cst.setString(3, edad);
 cst.setString(4, sueldo);
 int rpta=cst.executeUpdate();
 if(rpta==1){
 JOptionPane.showMessageDialog(this, "cliente encontrado","aviso",JOptionPane.INFORMATION_MESSAGE);
 this.jTextField1.setText("");
 this.jTextField2.setText("");
 this.jTextField3.setText("");
 this.jTextField5.setText("");
 }else
 {
 JOptionPane.showMessageDialog(this,"cliente no encontrado","aviso",JOptionPane.INFORMATION_MESSAGE);
 }
 }
 catch(Exception e){
 JOptionPane.showMessageDialog(this, e.toString());
 }
 } 
 private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) { 
 //buscar
 String cod=this.jTextField2.getText();
 try{
 cst=con.prepareCall("{call buscar(?)}");
 cst.setString(1, cod);
 r=cst.executeQuery();
 if(r.next()){
 JOptionPane.showMessageDialog(this,"cliente encontrado","aviso",JOptionPane.INFORMATION_MESSAGE);
 this.jTextField1.setText(r.getString(1));
 this.jTextField2.setText(r.getString(2));
 this.jTextField3.setText(r.getString(3));
 this.jTextField5.setText(r.getString(4)); }
 else
 {
 JOptionPane.showMessageDialog(this,"cliente no encontrado","aviso",JOptionPane.INFORMATION_MESSAGE);
 }
 }
 catch(Exception e){
 JOptionPane.showMessageDialog(this, e.toString());
 }
 } 
 private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) { 
 // TODO add your handling code here:
 } 
 private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) { 
 //boton modificar
 String cod=this.jTextField1.getText();
 String nom=this.jTextField2.getText();
 String edad=this.jTextField3.getText();
 String sueldo=this.jTextField5.getText();
 try{
 cst=con.prepareCall("{call modificar(?,?,?,?)}");
 cst.setString(1, cod);
 cst.setString(2, nom);
 cst.setString(3, edad);
 cst.setString(4, sueldo);
 int rpta=cst.executeUpdate();
 if(rpta==1){
 JOptionPane.showMessageDialog(this, "Cliente modificado","aviso",JOptionPane.INFORMATION_MESSAGE);
 this.jTextField1.setText("");
 this.jTextField2.setText("");
 this.jTextField3.setText("");
 this.jTextField5.setText("");
 }else
 {
 JOptionPane.showMessageDialog(this,"Error al modificar","aviso",JOptionPane.INFORMATION_MESSAGE);
 }
 }
 catch(Exception e){
 JOptionPane.showMessageDialog(this, e.toString());
 } } 
 private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) { 
 // TODO add your handling code here:
 } 
 /**
 * @param args the command line arguments
 */
 public static void main(String args[]) {
 /* Set the Nimbus look and feel */
 //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
 /* If Nimbus (introduced in Java SE 6) is not available, stay with the default
look and feel.
 * For details see 
http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
 */
 try {
 for (javax.swing.UIManager.LookAndFeelInfo info : 
javax.swing.UIManager.getInstalledLookAndFeels()) {
 if ("Nimbus".equals(info.getName())) {
 javax.swing.UIManager.setLookAndFeel(info.getClassName());
 break;
 }
 }
 } catch (ClassNotFoundException ex) {
 
java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 } catch (InstantiationException ex) {
 
java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 } catch (IllegalAccessException ex) {
 
java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 } catch (javax.swing.UnsupportedLookAndFeelException ex) {
 
java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 }
 //</editor-fold>
 /* Create and display the form */
 java.awt.EventQueue.invokeLater(new Runnable() {
 public void run() {
     try {
         new Formulario().setVisible(true);
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
     } catch (SQLException ex) {
         Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
     }
 } });
 }
 // Variables declaration - do not modify 
 private javax.swing.JButton jButton1;
 private javax.swing.JButton jButton2;
 private javax.swing.JButton jButton4;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JLabel jLabel3;
 private javax.swing.JLabel jLabel4;
 private javax.swing.JLabel jLabel5;
 private javax.swing.JTextField jTextField1;
 private javax.swing.JTextField jTextField2;
 private javax.swing.JTextField jTextField3;
 private javax.swing.JTextField jTextField5;
 // End of variables declaration 
}